// eslint-disable-next-line @typescript-eslint/no-var-requires
import * as logClient from "./logClient"

// eslint-disable-next-line @typescript-eslint/no-var-requires
const getCSV = require("get-csv")

export enum CoreCustomerStatusEnum {
    PENDING = "Pending",
    APPOINTMENT = "Appointment"
}


export type CSVCoreCustomerType = {
    _type?: string
    slug?: string
    isAutoGenerated?: boolean
    firstName: string,
    lastName: string,
    coreLink: string,
    appointmentDate: string,
    coreId: string,
    status: string,
    quoteLink: string,
    projectManager:string
    jobDate: string,
}

export type CSVThetaChiMemberType = {
    _type?: string
    slug?: string
    spreadsheetId: number
    firstName: string,
    title: string,
    middleName: string,
    lastName: string,
    nickName: string,
    semester?: string,
    year?: string,
    lineNumber?: string,
    crossingDate?: Date,
    nameOfLine: string,
    lineName?: string,
    dopName:string
    dob?: Date,
    spouse?: string,
    children?: string[],
    occupation?: string,
    address?: string,
    city?:string,
    state?:string,
    postalCode?:string,
    otherChapterAffiliation:string,
    homePhone?:string,
    workPhone?:string,
    cellPhone?:string,
    email?:string[]
    isChapterInvisible:boolean
    isOnTheYard:boolean
    isLivesOnCampus:boolean
    onCampusPosition?:string
}

export type CSVThetaChiMemberSpreadsheetType = {
    spreadsheetId: number
    name: string,
    year: string,
    crossingDate: Date,
    nameOfLine: string,
    lineName: string,
    dopName:string
    dob: Date,
    spouseChildren: string,
    occupation: string,
    address: string,
    city: string,
    homePhone:string,
    workPhone:string,
    cellPhone:string,
    email:string
}

const loadCSV = (url?: string) => {
    try {
        return url ? getCSV(url)
            .then((rows: any) => {
                logClient.log("loadCSV", "NOTICE", "rows retrieved from file", rows)
                return rows
            }) : ""
    } catch (e) {
        logClient.log("loadCSV", "ERROR", "rows NOT retrieved from file", e)
    }
}

export default {loadCSV}