export default {
    name: 'spreadsheetMember',
    title: 'Theta Chi Member',
    type: 'document',
    fields: [
        {
            name: 'title',
            title: 'Title(Jr, Sr)',
            type: 'string',
        },
        {
            name: 'firstName',
            title: 'First Name',
            type: 'string',
        },
        {
            name: 'middleName',
            title: 'Middle Name',
            type: 'string',
        },
        {
            name: 'lastName',
            title: 'Last Name',
            type: 'string',
        },
        {
            name: 'nickName',
            title: 'Nick Name',
            type: 'string',
        },
        {
            name: 'spreadsheetId',
            title: 'Original Id in spreadsheet',
            type: 'string',
        },
        {
            name: 'semester',
            title: 'Semester',
            type: 'string',
        },
        {
            name: 'address',
            title: 'Address',
            type: 'string',
        },
        {
            name: 'year',
            title: 'Year',
            type: 'number',
        },
        {
            name: 'city',
            title: 'City',
            type: 'string',
        },
        {
            name: 'postalCode',
            title: 'Postal Code',
            type: 'string',
        },
        {
            name: 'state',
            title: 'State',
            type: 'string',
        },
        {
            name: 'lineNumber',
            title: 'Line Number',
            type: 'string',
        },
        {
            name: 'crossingDate',
            title: 'Crossing Date',
            type: 'date',
        },
        {
            name: 'dob',
            title: 'DOB',
            type: 'date',
        },
        {
            name: 'nameOfLine',
            title: 'Name of Line',
            type: 'string',
        },
        {
            name: 'lineName',
            title: 'Line Name',
            type: 'string',
        },
        {
            name: 'dopName',
            title: 'Dop Name',
            type: 'string',
        },
        {
            name: 'spouse',
            title: 'Spouse',
            type: 'string',
        },
        {
            name: 'children',
            title: 'Children',
            type: 'array',
            of:[{type:'string'}]
        },
        {
            name: 'occupation',
            title: 'Occupation',
            type: 'string',
        },
        {
            name: 'email',
            title: 'E-mail',
            type: 'string',
        },
        {
            name: 'homePhone',
            title: 'Home Phone',
            type: 'string',
        },
        {
            name: 'workPhone',
            title: 'Work Phone',
            type: 'string',
        },
        {
            name: 'cellPhone',
            title: 'Cell Phone',
            type: 'string',
        },
        {
            name: 'isAutoGenerated',
            title: 'Uploaded via Csv',
            type: 'boolean',
        },
        {
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            options: {
                maxLength: 96,
            },
        },
    ],
};