export default {
    name: 'spreadsheetMember',
    title: 'Theta Chi Member',
    type: 'document',
    fields: [
        {
            name: 'spreadsheetId',
            title: 'Original Id in spreadsheet',
            type: 'string',
        },
        {
            name: 'slug',
            title: 'Slug',
            type: 'slug',
            options: {
                maxLength: 96,
            },
        },
        {
            name: 'isAutoGenerated',
            title: 'Uploaded via Csv',
            type: 'boolean',
        },
        {
            name: 'isChapterInvisible',
            title: 'Is Chapter Invisible',
            type: 'boolean',
        },
        {
            name: 'isOnTheYard',
            title: 'Is on the yard',
            type: 'boolean',
        },
        {
            name: 'isLivesOnCampus',
            title: 'Lives on Campus?',
            type: 'boolean',
        },
        {
            name: 'onCampusPosition',
            title: 'Current Position',
            type: 'string',
        },
        {
            name: 'firstName',
            title: 'First Name',
            type: 'string',
        },
        {
            name: 'middleName',
            title: 'Middle Name',
            type: 'string',
        },
        {
            name: 'lastName',
            title: 'Last Name',
            type: 'string',
        },
        {
            name: 'nickName',
            title: 'Nick Name',
            type: 'string',
        },
        {
            name: 'title',
            title: 'Title(Jr, Sr)',
            type: 'string',
        },
        {
            name: 'email',
            title: 'E-mail',
            type: 'array',
            of: [{type: 'string',}]
        },
        {
            name: 'cellPhone',
            title: 'Cell Phone',
            type: 'string',
        },
        {
            name: 'otherChapterAffiliation',
            title: 'Chapter Affiliation',
            type: 'string',
        },
        {
            name: 'crossingDate',
            title: 'Crossing Date',
            type: 'date',
        },
        {
            name: 'semester',
            title: 'Semester',
            type: 'string',
        },
        {
            name: 'year',
            title: 'Year',
            type: 'string',
        },
        {
            name: 'nameOfLine',
            title: 'Name of Line',
            type: 'string',
        },
        {
            name: 'lineName',
            title: 'Line Name',
            type: 'string',
        },
        {
            name: 'lineNumber',
            title: 'Line Number',
            type: 'string',
        },
        {
            name: 'dopName',
            title: 'Dop Name',
            type: 'string',
        },
        {
            name: 'address',
            title: 'Address',
            type: 'string',
        },
        {
            name: 'city',
            title: 'City',
            type: 'string',
        },
        {
            name: 'postalCode',
            title: 'Postal Code',
            type: 'string',
        },
        {
            name: 'state',
            title: 'State',
            type: 'string',
        },
        {
            name: 'occupation',
            title: 'Occupation',
            type: 'string',
        },
        {
            name: 'spouse',
            title: 'Spouse',
            type: 'string',
        },
        {
            name: 'children',
            title: 'Children',
            type: 'array',
            of:[{type:'string'}]
        },
        {
            name: 'homePhone',
            title: 'Home Phone',
            type: 'string',
        },
        {
            name: 'workPhone',
            title: 'Work Phone',
            type: 'string',
        },
        {
            name: 'dob',
            title: 'DOB',
            type: 'date',
        },
    ],
    preview: {
        select: {
            semester: 'semester',
            year: 'year',
            lineNumber: 'lineNumber',
            lastName: 'lastName',
            firstName: 'firstName'
        },
        prepare(selection) {
            const { semester, year, lineNumber, lastName, firstName } = selection;
             console.log("Selection ? ", selection)
            return { ...selection, title:` ${firstName}  ${lastName} `,subtitle: `${semester} ${year} ${lineNumber}` };
        },
    },
};